#! /usr/bin/python
# encoding: utf-8

import os

APPNAME="miao"
VERSION=0.6
OUTDIR='exes'
ZIPDIR='zips'
out='results'
LICENSE="OFL.txt"
sourcedir='source/'

langmap = {
   'hmd' : [['hmdUni'],['Shimenkan-OT']],
   'lpo' : [['lpoUni'],['Taogu-OT']]
}

for l in langmap.keys():
	fontname = langmap[l][1][0]
	keyboardname = langmap[l][0][0]
	cmds = [cmd('ttfdeflang -d ' + l + ' ${DEP} ${TGT}'), name(fontname, lang='en-US')]
	if os.path.exists(os.path.join(sourcedir, l+'map.cfg')) :
        	cmds.append(cmd('ttfremap -c ${SRC} -r ${DEP} ${TGT}', [sourcedir + l + 'map.cfg']))
	font(
     target=process('fonts/' + fontname + '.ttf', *cmds),
	source=sourcedir + APPNAME + '.sfd',
#    graphite=gdl('fonts/' + l + '.gdl', master=sourcedir + l + '.gdl', params="-d -q -w3521", make_params="-r"),
    opentype = fea("miao.fea", master="source/miao.fea", old_make_fea = True, make_params="-z 8"),

    script = 'plrd'
)

